### ISSUE TITLE
"make" error

### ISSUE THREAD

**Issue by mrold** [garvins/php-git#5]
My English is not good.When I execute the 'make' command, this show me a error. Please see the print thing:
In file included from /home/vagrant/php-git-php7/php_git2.c:26:0:
/home/vagrant/php-git-php7/php_git2.h:47:18: fatal error: git2.h: No such file or directory
compilation terminated.
Makefile:195: recipe for target 'php_git2.lo' failed
make: *** [php_git2.lo] Error 1

**Comment by garvins** [comment]
Hi @mrold,

this souds like, that the submodule is empty or not initialized.
Use `git submodule init && git submodule update` to download all.

**Comment by mrold** [comment]
@garvins I realized that this may require a lot of work to be successful, I used gitlab api as an alternative. Anyway, thank you very much!
